[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<src/>
    +<include/>


lib_deps =
    Servo
    fastled/FastLED@^3.10.3

;build_src_filter =
;   +<*.cpp>
;   +<ELEGOO*/TB6612/*>
;    +<SlamFunctionSet.cpp>
;    -<**/DRV8835*>
;    -<**/ESP32*>
;    -<**/Camera*>
